---
title: "Bubble Chart"
author: "Hanna Rodrigues Ferreira"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: 
  prettydoc::html_pretty:
    theme: architect
    highlight: github
    df_print: kable
---

```{r setup, include=FALSE,warning=FALSE}

knitr::opts_chunk$set(echo = TRUE)
library(plotly)
library(tidyverse)
library(lubridate)

```



```{r clean}

data <- read.csv("owid-covid-data.csv")

data <- data %>% mutate(cases = total_cases, 
                        deaths = total_deaths,
                        vac1 = people_vaccinated,
                        vac2 = people_fully_vaccinated,
                        pop = population)

data <- data %>% select(continent,
                        location,
                        cases,
                        deaths,
                        vac1,
                        vac2,
                        date,
                        pop)

data <- data %>% filter(!(location %in% c("World",
                                         "Asia",
                                         "Europe",
                                         "North America",
                                         "European Union",
                                         "South America",
                                         "Africa",
                                         "Oceania",
                                         "International",
                                         "Northern Cyprus"))) #NA's

glimpse(data)

```

```{r}

summary(data)

```

```{r fill}

data <- data %>%
  mutate(date_aux = as.Date(date)) %>%
  filter(date_aux>"2020-01-01") %>%
  group_by(location, month(date_aux)) %>%
  filter(date_aux == max(date_aux))

data <- data %>%
    group_by(location) %>%
    fill(cases,
         deaths,
         vac1,
         vac2, .direction = c("down"))

```

```{r}

summary(data)

```

```{r nan}

data <- data %>%
        group_by(location) %>%
        mutate(cases = 100*replace_na(cases,0)/pop,
               deaths = 100*replace_na(deaths,0)/pop,
               vac1 = 100*replace_na(vac1,0)/pop,
               vac2 = 100*replace_na(vac2,0)/pop)

data<- data %>% mutate(date_num = as.numeric(date_aux))


data <- data %>% select(-pop)

data <- data %>%
    group_by(location) %>%
    fill(cases,
         deaths,
         vac1,
         vac2, .direction = c("down"))

```

```{r}

summary(data)

```

```{r}

glimpse(data)

```


```{r}



```

```{r}



```

```{r}

```

```{r external data}

names <- c('Brazil',
           'United States',
           'Canada',
           'Mexico',
           'Germany',
           'United Kingdom',
           'French',
           'Italy',
           'Spain',
           'Russia',
           'India',
           'South Korea',
           'China',
           'Japan',
           'Australia')


colors <- c('gray',
            '#F28B30', # Asia (laranja)
            '#BF0A3A', # Europa (vermelho)
            '#022873', # Am?rica do norte (azul)
            '#F23D6D', # Oceania (rosa)    
            '#03A62C', # Am?rica do sul
            'yellow')    # Outros (cinza)

```


```{r}

data <- mutate(data, Continent=ifelse(location %in% names,
                                      continent,
                                      as_factor("Others")))

```

```{r plot}

p <- data %>%
  ggplot(aes(x=cases,
             y=deaths,
             size=vac2)) +
  geom_point(aes(color=as_factor(Continent),
                 frame=date_num,
                 ids=location),alpha=0.6) +
  scale_x_continuous(limits = c(-1.5, 20)) +
  scale_y_continuous(limits = c(-0.09, .65)) +
  scale_size(range = c(.1, 25), name="fully vaccinated") +
  scale_colour_manual(values = colors) +
  theme_classic() +
  labs(title="COVID-19 vaccinations of top 15 GPD countries") +
  theme(legend.position="none")


```

```{r}

p

```

```{r}

ggplotly(p,tooltip = "text") %>% animation_opts(700,
                               redraw = FALSE,
                               mode = 'afterall') %>%
  animation_button(x = 1, xanchor = "right",
                   y = 0.05, yanchor = "bottom") %>% 
  animation_slider(hide = TRUE)

```


```{r}

fig <- plot_ly(data,
               x = ~cases,
               y = ~deaths,
               color = ~Continent,
               size = ~vac2,
               colors = colors,
        type = 'scatter',
        mode = 'markers',
        sizes = c(0.1, 24),
        marker = list(symbol = 'circle', sizemode = 'diameter',
                      line = list(width = 2, color = '#FFFFFF')),
        text = ~paste('Country:', location,
                      '<br>Continent:', continent,
                      '<br>Fully Vaccinated:', vac2))

fig

```

```{r}

# fig <- df %>%
#   plot_ly(
#     x = ~gdpPercap, 
#     y = ~lifeExp, 
#     size = ~pop, 
#     color = ~continent, 
#     frame = ~year, 
#     text = ~country, 
#     hoverinfo = "text",
#     type = 'scatter',
#     mode = 'markers'
#   )
# fig <- fig %>% layout(
#     xaxis = list(
#       type = "log"
#     )
#   )
# 
# fig
  


```
